/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedExploreRouteImport } from './routes/_authenticated/explore'
import { Route as AuthenticatedComingSoonRouteImport } from './routes/_authenticated/coming-soon'
import { Route as AuthenticatedChangelogRouteImport } from './routes/_authenticated/changelog'
import { Route as AuthenticatedUserUsernameRouteImport } from './routes/_authenticated/user.$username'
import { Route as AuthenticatedTvIdRouteImport } from './routes/_authenticated/tv.$id'
import { Route as AuthenticatedPersonIdRouteImport } from './routes/_authenticated/person.$id'
import { Route as AuthenticatedMovieIdRouteImport } from './routes/_authenticated/movie.$id'
import { Route as AuthenticatedListIdRouteImport } from './routes/_authenticated/list.$id'
import { Route as AuthenticatedWatchMediaTypeIdRouteImport } from './routes/_authenticated/watch.$mediaType.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExploreRoute = AuthenticatedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComingSoonRoute = AuthenticatedComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChangelogRoute = AuthenticatedChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUserUsernameRoute =
  AuthenticatedUserUsernameRouteImport.update({
    id: '/user/$username',
    path: '/user/$username',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTvIdRoute = AuthenticatedTvIdRouteImport.update({
  id: '/tv/$id',
  path: '/tv/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPersonIdRoute = AuthenticatedPersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMovieIdRoute = AuthenticatedMovieIdRouteImport.update({
  id: '/movie/$id',
  path: '/movie/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedListIdRoute = AuthenticatedListIdRouteImport.update({
  id: '/list/$id',
  path: '/list/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWatchMediaTypeIdRoute =
  AuthenticatedWatchMediaTypeIdRouteImport.update({
    id: '/watch/$mediaType/$id',
    path: '/watch/$mediaType/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot': typeof ForgotRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/changelog': typeof AuthenticatedChangelogRoute
  '/coming-soon': typeof AuthenticatedComingSoonRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/list/$id': typeof AuthenticatedListIdRoute
  '/movie/$id': typeof AuthenticatedMovieIdRoute
  '/person/$id': typeof AuthenticatedPersonIdRoute
  '/tv/$id': typeof AuthenticatedTvIdRoute
  '/user/$username': typeof AuthenticatedUserUsernameRoute
  '/watch/$mediaType/$id': typeof AuthenticatedWatchMediaTypeIdRoute
}
export interface FileRoutesByTo {
  '/forgot': typeof ForgotRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/changelog': typeof AuthenticatedChangelogRoute
  '/coming-soon': typeof AuthenticatedComingSoonRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/list/$id': typeof AuthenticatedListIdRoute
  '/movie/$id': typeof AuthenticatedMovieIdRoute
  '/person/$id': typeof AuthenticatedPersonIdRoute
  '/tv/$id': typeof AuthenticatedTvIdRoute
  '/user/$username': typeof AuthenticatedUserUsernameRoute
  '/watch/$mediaType/$id': typeof AuthenticatedWatchMediaTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_authenticated/changelog': typeof AuthenticatedChangelogRoute
  '/_authenticated/coming-soon': typeof AuthenticatedComingSoonRoute
  '/_authenticated/explore': typeof AuthenticatedExploreRoute
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/list/$id': typeof AuthenticatedListIdRoute
  '/_authenticated/movie/$id': typeof AuthenticatedMovieIdRoute
  '/_authenticated/person/$id': typeof AuthenticatedPersonIdRoute
  '/_authenticated/tv/$id': typeof AuthenticatedTvIdRoute
  '/_authenticated/user/$username': typeof AuthenticatedUserUsernameRoute
  '/_authenticated/watch/$mediaType/$id': typeof AuthenticatedWatchMediaTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot'
    | '/signin'
    | '/signup'
    | '/changelog'
    | '/coming-soon'
    | '/explore'
    | '/friends'
    | '/search'
    | '/settings'
    | '/list/$id'
    | '/movie/$id'
    | '/person/$id'
    | '/tv/$id'
    | '/user/$username'
    | '/watch/$mediaType/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot'
    | '/signin'
    | '/signup'
    | '/changelog'
    | '/coming-soon'
    | '/explore'
    | '/friends'
    | '/search'
    | '/settings'
    | '/'
    | '/list/$id'
    | '/movie/$id'
    | '/person/$id'
    | '/tv/$id'
    | '/user/$username'
    | '/watch/$mediaType/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot'
    | '/signin'
    | '/signup'
    | '/_authenticated/changelog'
    | '/_authenticated/coming-soon'
    | '/_authenticated/explore'
    | '/_authenticated/friends'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/list/$id'
    | '/_authenticated/movie/$id'
    | '/_authenticated/person/$id'
    | '/_authenticated/tv/$id'
    | '/_authenticated/user/$username'
    | '/_authenticated/watch/$mediaType/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotRoute: typeof ForgotRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coming-soon': {
      id: '/_authenticated/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof AuthenticatedComingSoonRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/changelog': {
      id: '/_authenticated/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof AuthenticatedChangelogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/user/$username': {
      id: '/_authenticated/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof AuthenticatedUserUsernameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tv/$id': {
      id: '/_authenticated/tv/$id'
      path: '/tv/$id'
      fullPath: '/tv/$id'
      preLoaderRoute: typeof AuthenticatedTvIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/person/$id': {
      id: '/_authenticated/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof AuthenticatedPersonIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/movie/$id': {
      id: '/_authenticated/movie/$id'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof AuthenticatedMovieIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/list/$id': {
      id: '/_authenticated/list/$id'
      path: '/list/$id'
      fullPath: '/list/$id'
      preLoaderRoute: typeof AuthenticatedListIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/watch/$mediaType/$id': {
      id: '/_authenticated/watch/$mediaType/$id'
      path: '/watch/$mediaType/$id'
      fullPath: '/watch/$mediaType/$id'
      preLoaderRoute: typeof AuthenticatedWatchMediaTypeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedChangelogRoute: typeof AuthenticatedChangelogRoute
  AuthenticatedComingSoonRoute: typeof AuthenticatedComingSoonRoute
  AuthenticatedExploreRoute: typeof AuthenticatedExploreRoute
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedListIdRoute: typeof AuthenticatedListIdRoute
  AuthenticatedMovieIdRoute: typeof AuthenticatedMovieIdRoute
  AuthenticatedPersonIdRoute: typeof AuthenticatedPersonIdRoute
  AuthenticatedTvIdRoute: typeof AuthenticatedTvIdRoute
  AuthenticatedUserUsernameRoute: typeof AuthenticatedUserUsernameRoute
  AuthenticatedWatchMediaTypeIdRoute: typeof AuthenticatedWatchMediaTypeIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChangelogRoute: AuthenticatedChangelogRoute,
  AuthenticatedComingSoonRoute: AuthenticatedComingSoonRoute,
  AuthenticatedExploreRoute: AuthenticatedExploreRoute,
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedListIdRoute: AuthenticatedListIdRoute,
  AuthenticatedMovieIdRoute: AuthenticatedMovieIdRoute,
  AuthenticatedPersonIdRoute: AuthenticatedPersonIdRoute,
  AuthenticatedTvIdRoute: AuthenticatedTvIdRoute,
  AuthenticatedUserUsernameRoute: AuthenticatedUserUsernameRoute,
  AuthenticatedWatchMediaTypeIdRoute: AuthenticatedWatchMediaTypeIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotRoute: ForgotRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
